version: 2.1
jobs:
  get:
    docker:
      - image: honeysnow/tester
    working_directory: ~/repo/
    steps:
      - checkout:
          path: ~/repo
      - restore_cache: # Restore modules from previous builds.
          keys:
            - dependencies-{{ checksum "package.json" }}-{{ checksum "scanner_reader/requirements.txt" }}
            - dependencies-{{ checksum "package.json" }}
            - dependencies-{{ checksum "scanner_reader/requirements.txt" }}
      - run:
          name: Install node dependencies
          command: make dependencies
      - save_cache: # Cache modules between builds.
          paths:
            - ./node_modules
          key: dependencies-{{ checksum "package.json" }}
      - run:
          name: Source venv
          command: virtualenv -p python2.7 scanner_reader/venv && echo "source scanner_reader/venv/bin/activate" >> $BASH_ENV
      - run:
          name: Install python dependencies
          command: pip install -r scanner_reader/requirements.txt
      - save_cache: # Cache modules between builds.
          paths:
            - ./scanner_reader/venv
          key: dependencies-{{ checksum "scanner_reader/requirements.txt" }}
      - save_cache: # Cache modules between builds.
          paths:
            - ./scanner_reader/venv
            - ./node_modules
          key: dependencies-{{ checksum "package.json" }}-{{ checksum "scanner_reader/requirements.txt"}}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - "*"
  deploy-serverless:
    docker:
      - image: honeysnow/tester
    working_directory: ~/repo/
    parameters:
      stage:
        type: string
        default: dev
    steps:
      - attach_workspace:
          at: ~/repo
      - deploy:
          name: Start << parameters.stage >> deployment
          command: make deploy-<< parameters.stage >>
  deploy-group:
    docker:
      - image: honeysnow/tester
    working_directory: ~/repo/
    parameters:
      stage:
        type: string
        default: dev
    steps:
      - attach_workspace:
          at: ~/repo
      - deploy:
          name: Start << parameters.stage >> deployment
          command: node deploy-group.js

workflows:
  version: 2.1
  build:
    jobs:
      - get
      - deploy-serverless:
          stage: dev
          requires:
            - get
          filters:
            branches:
              only:
                - master
      - deploy-group:
          stage: dev
          requires:
            - deploy-serverless
          filters:
            branches:
              only:
                - master