version: 2.1
jobs:
  get:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo/
    steps:
      - checkout:
          path: ~/repo
      - restore_cache: # Restore modules from previous builds.
          keys:
            - node-modules-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache: # Cache modules between builds.
          paths:
            - ./node_modules
          key: node-modules-{{ checksum "package.json" }}
      - persist_to_workspace:
          root: ~/repo
          paths:
            - "*"
  deploy-serverless:
    docker:
      - image: circleci/node:8.10
    working_directory: ~/repo/
    parameters:
      stage:
        type: string
        default: dev
    steps:
      - attach_workspace:
          at: ~/repo
      - deploy:
          name: Start << parameters.stage >> deployment
          command: make deploy-<< parameters.stage >>

workflows:
  version: 2.1
  build:
    jobs:
      - get
      - deploy-serverless:
          stage: dev
          requires:
            - get
          filters:
            branches:
              only:
                - master